services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proyecto
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}  
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=$(DB_DATABASE)
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
