# Exported from Render
services:
- type: web
  name: proyecto
  runtime: docker
  repo: https://github.com/ivaan08082004/proyecto
  plan: free
  numInstances: 2  # Número fijo de instancias para balanceo

  envVars:
  - key: REDIS_PORT
    sync: false
  - key: REDIS_PASSWORD
    sync: false
  # Resto de variables aquí...
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile


