services:
  - type: web
    name: proyecto-laravel
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://proyecto-h7qn.onrender.com
      - key: APP_KEY
        value: base64:HMZ6XNx4Qp7xjzniMtFTZ7hVxg+vcKL0zuWCxAH/jxo=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromService:
          type: pserv
          name: proyecto-db
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: proyecto
      - key: DB_USERNAME
        value: proyecto_user
      - key: DB_PASSWORD
        value: proyecto_user
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file

databases:
  - name: proyecto-db
    region: frankfurt
    plan: free
    databaseName: proyecto
    user: proyecto_user
    password: proyecto_user
